name: ci-vipc

on:
  push:
    branches:
      - main
      - dev
    # paths: |
    #   ./**/*.vipc
  workflow_dispatch:

jobs:

  ci-vipc:
    uses: vipm-io/OpenG-Tookit/.github/workflows/ci-container.yml@main
    secrets: inherit
    with:
      labview-version: 2024

